import 'dart:ui';

import 'onscreen_gamepad_models.dart';

const kOnscreenGamepadXboxProfile = OnscreenGamepadProfile(
  id: 'xbox-default',
  name: 'Xbox Default',
  defaultColor: Color(0xFF090E16),
  backgroundOpacity: 0.36,
  foregroundOpacity: 0.60,
  controls: [
    OnscreenGamepadControl(
      id: 'left-stick',
      label: 'LS',
      anchor: OnscreenGamepadAnchor.bottomLeft,
      offset: Offset(-0.20, 0.42),
      kind: OnscreenGamepadControlKind.stick,
      role: OnscreenGamepadControlRole.stick,
      sizeTier: OnscreenGamepadSizeTier.large,
      input: OnscreenGamepadInput.gamepadStick(
        code: 'leftStick',
        xAxis: 'leftX',
        yAxis: 'leftY',
        buttonCode: 'leftStickButton',
      ),
      sortOrder: 10,
    ),
    OnscreenGamepadControl(
      id: 'right-stick',
      label: 'RS',
      anchor: OnscreenGamepadAnchor.bottomRight,
      offset: Offset(-0.35, 0.46),
      kind: OnscreenGamepadControlKind.stick,
      role: OnscreenGamepadControlRole.stick,
      sizeTier: OnscreenGamepadSizeTier.large,
      input: OnscreenGamepadInput.gamepadStick(
        code: 'rightStick',
        xAxis: 'rightX',
        yAxis: 'rightY',
        buttonCode: 'rightStickButton',
      ),
      sizeScale: 0.9,
      sortOrder: 20,
    ),
    OnscreenGamepadControl(
      id: 'dpad-up',
      label: 'DU',
      anchor: OnscreenGamepadAnchor.bottomLeft,
      offset: Offset(0.20, -0.56),
      kind: OnscreenGamepadControlKind.square,
      role: OnscreenGamepadControlRole.dpad,
      sizeTier: OnscreenGamepadSizeTier.small,
      input: OnscreenGamepadInput.gamepadButton('dpadUp'),
      sizeScale: 0.9,
      sortOrder: 30,
    ),
    OnscreenGamepadControl(
      id: 'dpad-left',
      label: 'DL',
      anchor: OnscreenGamepadAnchor.bottomLeft,
      offset: Offset(-0.15, -0.24),
      kind: OnscreenGamepadControlKind.square,
      role: OnscreenGamepadControlRole.dpad,
      sizeTier: OnscreenGamepadSizeTier.small,
      input: OnscreenGamepadInput.gamepadButton('dpadLeft'),
      sizeScale: 0.9,
      sortOrder: 31,
    ),
    OnscreenGamepadControl(
      id: 'dpad-right',
      label: 'DR',
      anchor: OnscreenGamepadAnchor.bottomLeft,
      offset: Offset(0.55, -0.24),
      kind: OnscreenGamepadControlKind.square,
      role: OnscreenGamepadControlRole.dpad,
      sizeTier: OnscreenGamepadSizeTier.small,
      input: OnscreenGamepadInput.gamepadButton('dpadRight'),
      sizeScale: 0.9,
      sortOrder: 32,
    ),
    OnscreenGamepadControl(
      id: 'dpad-down',
      label: 'DD',
      anchor: OnscreenGamepadAnchor.bottomLeft,
      offset: Offset(0.20, 0.09),
      kind: OnscreenGamepadControlKind.square,
      role: OnscreenGamepadControlRole.dpad,
      sizeTier: OnscreenGamepadSizeTier.small,
      input: OnscreenGamepadInput.gamepadButton('dpadDown'),
      sizeScale: 0.9,
      sortOrder: 33,
    ),
    OnscreenGamepadControl(
      id: 'x',
      label: 'X',
      anchor: OnscreenGamepadAnchor.bottomRight,
      offset: Offset(0.00, -0.42),
      kind: OnscreenGamepadControlKind.circle,
      role: OnscreenGamepadControlRole.secondary,
      sizeTier: OnscreenGamepadSizeTier.medium,
      input: OnscreenGamepadInput.gamepadButton('x'),
      sortOrder: 40,
    ),
    OnscreenGamepadControl(
      id: 'y',
      label: 'Y',
      anchor: OnscreenGamepadAnchor.bottomRight,
      offset: Offset(0.36, -0.68),
      kind: OnscreenGamepadControlKind.circle,
      role: OnscreenGamepadControlRole.secondary,
      sizeTier: OnscreenGamepadSizeTier.medium,
      input: OnscreenGamepadInput.gamepadButton('y'),
      sortOrder: 41,
    ),
    OnscreenGamepadControl(
      id: 'a',
      label: 'A',
      anchor: OnscreenGamepadAnchor.bottomRight,
      offset: Offset(0.36, -0.16),
      kind: OnscreenGamepadControlKind.circle,
      role: OnscreenGamepadControlRole.primary,
      sizeTier: OnscreenGamepadSizeTier.medium,
      input: OnscreenGamepadInput.gamepadButton('a'),
      sortOrder: 42,
    ),
    OnscreenGamepadControl(
      id: 'b',
      label: 'B',
      anchor: OnscreenGamepadAnchor.bottomRight,
      offset: Offset(0.72, -0.42),
      kind: OnscreenGamepadControlKind.circle,
      role: OnscreenGamepadControlRole.secondary,
      sizeTier: OnscreenGamepadSizeTier.medium,
      input: OnscreenGamepadInput.gamepadButton('b'),
      sortOrder: 43,
    ),
    OnscreenGamepadControl(
      id: 'lb',
      label: 'LB',
      anchor: OnscreenGamepadAnchor.bottomLeft,
      offset: Offset(-0.38, -0.98),
      kind: OnscreenGamepadControlKind.square,
      role: OnscreenGamepadControlRole.bumper,
      sizeTier: OnscreenGamepadSizeTier.medium,
      input: OnscreenGamepadInput.gamepadButton('leftShoulder'),
      sortOrder: 50,
    ),
    OnscreenGamepadControl(
      id: 'lt',
      label: 'LT',
      anchor: OnscreenGamepadAnchor.bottomLeft,
      offset: Offset(0.08, -0.98),
      kind: OnscreenGamepadControlKind.square,
      role: OnscreenGamepadControlRole.trigger,
      sizeTier: OnscreenGamepadSizeTier.medium,
      input: OnscreenGamepadInput.gamepadButton('leftTrigger'),
      sortOrder: 51,
    ),
    OnscreenGamepadControl(
      id: 'rb',
      label: 'RB',
      anchor: OnscreenGamepadAnchor.bottomRight,
      offset: Offset(-0.08, -0.98),
      kind: OnscreenGamepadControlKind.square,
      role: OnscreenGamepadControlRole.bumper,
      sizeTier: OnscreenGamepadSizeTier.medium,
      input: OnscreenGamepadInput.gamepadButton('rightShoulder'),
      sortOrder: 52,
    ),
    OnscreenGamepadControl(
      id: 'rt',
      label: 'RT',
      anchor: OnscreenGamepadAnchor.bottomRight,
      offset: Offset(0.38, -0.98),
      kind: OnscreenGamepadControlKind.square,
      role: OnscreenGamepadControlRole.trigger,
      sizeTier: OnscreenGamepadSizeTier.medium,
      input: OnscreenGamepadInput.gamepadButton('rightTrigger'),
      sortOrder: 53,
    ),
    OnscreenGamepadControl(
      id: 'view',
      label: 'View',
      anchor: OnscreenGamepadAnchor.bottomCenter,
      offset: Offset(-0.40, -0.40),
      kind: OnscreenGamepadControlKind.square,
      role: OnscreenGamepadControlRole.utility,
      sizeTier: OnscreenGamepadSizeTier.small,
      input: OnscreenGamepadInput.gamepadButton('view'),
      sizeScale: 0.85,
      sortOrder: 60,
    ),
    OnscreenGamepadControl(
      id: 'menu',
      label: 'Menu',
      anchor: OnscreenGamepadAnchor.bottomCenter,
      offset: Offset(0.40, -0.40),
      kind: OnscreenGamepadControlKind.square,
      role: OnscreenGamepadControlRole.utility,
      sizeTier: OnscreenGamepadSizeTier.small,
      input: OnscreenGamepadInput.gamepadButton('menu'),
      sizeScale: 0.85,
      sortOrder: 61,
    ),
    OnscreenGamepadControl(
      id: 'xbox',
      label: 'Xbox',
      anchor: OnscreenGamepadAnchor.bottomCenter,
      offset: Offset(0.00, 0.18),
      kind: OnscreenGamepadControlKind.circle,
      role: OnscreenGamepadControlRole.utility,
      sizeTier: OnscreenGamepadSizeTier.small,
      input: OnscreenGamepadInput.gamepadButton('guide'),
      sizeScale: 0.9,
      sortOrder: 62,
    ),
  ],
);
